# Generated by Django 2.2 on 2020-10-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(default='Inset you descrpition here', max_length=500),
        ),
    ]
